name: "Taplo Action"
author: "Gwen Lg"
description: "Run check and/or lint on TOML files with Taplo."

inputs:
  version:
    description: "Version of Taplo"
    required: false
    default: "0.10.0"
  format:
    description: "Check formatting TOML files"
    required: false
    default: "true"
  format_write_changes:
    description: "Write the formatting changes to the repository"
    required: false
    default: "false"
  lint:
    description: "Check TOML files with lints"
    required: false
    default: "false"
  archive:
    description: "Name of the Taplo archive"
    required: false
    default: "taplo-linux-x86_64"

runs:
  using: "composite"
  steps:
    - name: Install Taplo
      id: install
      shell: bash
      env:
        INSTALL_DIR: .
      run: |
        curl -Ls "https://github.com/tamasfe/taplo/releases/download/${{ inputs.version }}/${{ inputs.archive }}.gz" | \
        gzip -d > taplo && \
        chmod +x taplo && \
        sudo mv taplo /usr/local/bin/taplo

    - name: Format with Taplo
      if: ${{ inputs.format == 'true' }}
      id: format
      shell: bash
      run: |
        if ! ${{ inputs.format_write_changes }}; then
            ARGS=" --check --diff"
        fi
        taplo format ${ARGS}
    - name: Lint with Taplo
      if: ${{ inputs.lint == 'true' }}
      id: lint
      shell: bash
      run: taplo lint

branding:
  icon: "type"
  color: "red"
