on:
  workflow_call:

jobs:
  list-commits:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      nbcommits: ${{ steps.compute-commits-number.outputs.nbcommits }}
      commits: ${{ github.event.commits }}
    steps:
      - name: Compute commits number
        id: compute-commits-number
        run: |
          nbcommits=$(( ${{ github.event.commits }} + 1 ))
          echo "nbcommits=${nbcommits}" >> "$GITHUB_OUTPUT"
