name: Continuous Integration

on:
  push:
    branches-ignore:
      - "wip*"
  workflow_dispatch:

jobs:
  check-changelog:
    name: Various check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        id: generate-changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG_REF.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Check Changelog
        id: check-changelog
        run: diff CHANGELOG.md CHANGELOG_REF.md
