name: Test list-commits-action

on: [pull_request, push]

jobs:
  list-commits-action:
    runs-on: ubuntu-latest
    steps:
      - uses: gwen-lg/list-commits-action@eb10ea3d85c99033e5e0b5b8e7a7c70fc7c9ba60
