name: Test list-commits-action

on: [pull_request, push]

jobs:
  list-commits-action:
    runs-on: ubuntu-latest
    steps:
      - uses: gwen-lg/list-commits-action@753cfdde8020c22253d3916e7336040d2929de61
