name: Pull Request verification

on: [pull_request]

jobs:
  check-conventional-commits:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    concurrency:
      # For a given workflow, if we push to the same branch, cancel all previous builds on that branch.
      # Particularly useful for workflow triggered on release-plz sync.
      # release-plz workflow update de pending pr twice (with cargo readme update)
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0
