name: Pull Request verification

on: [pull_request]

jobs:
  check-conventional-commits:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    concurrency:
      # For a given workflow, if we push to the same branch, cancel all previous builds on that branch.
      # Particularly useful for workflow triggered on release-plz sync.
      # release-plz workflow update de pending pr twice (with cargo readme update)
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0

  commits-number:
    runs-on: ubuntu-latest
    outputs:
      nbcommits: ${{ steps.compute-commits-number.outputs.nbcommits }}
    steps:
      - name: Compute commits number
        id: compute-commits-number
        run: |
          nbcommits=$(( ${{ github.event.pull_request.commits }} + 1 ))
          echo "nbcommits=${nbcommits}" >> "$GITHUB_OUTPUT"

  define-matrix:
    needs: commits-number
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.list_commits.outputs.commits }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ needs.commits-number.outputs.nbcommits }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: List commits
        id: list_commits
        run: |
          set -eu
          for commit in $(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
            if [[ -v commit_list ]]
            then
              commit_list="$commit_list, \"$commit\""
            else
              commit_list="[ \"$commit\""
            fi
          done
          commit_list="$commit_list ]"
          echo "commits=${commit_list}" >> "$GITHUB_OUTPUT"

  check-changelog:
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        commit: ${{ fromJSON(needs.define-matrix.outputs.commits) }}

    name: "Check: ${{ matrix.commit }}"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.commit }}
      cancel-in-progress: true
    steps:
      - name: "Checkout `${{ matrix.commit }}`"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ matrix.commit }}"

      - name: Generate Changelog
        id: generate-changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG_UP.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Check Changelog
        id: check-changelog
        run: diff CHANGELOG.md CHANGELOG_UP.md
